version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: osm-fr/osmose_frontend
    ports:
      - 20009:20009
    environment:
      - URL_FRONTEND=frontend:20009
      #- OSMOSE_UNLOCKED_UPDATE=on
